module.exports = {
	"lenny": "( ͡° ͜ʖ ͡°)",
	"tableflip": "(╯°□°)╯︵ ┻━┻",
	"shrug": "¯\\_(ツ)_/¯",
	"bear": "ʕ•ᴥ•ʔ",
	"madflip": "(ノಠ益ಠ)ノ彡┻━┻",
	"rageflip": "┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻",
	"unflip": "┬──┬ ノ( ゜-゜ノ)",
	"bruh": "(；一_一)",
	"humanflip": "(╯°□°)╯︵( .o.)",
	"scared": "(ʘᗩʘ')",
	"unamused": "(¬_¬)",
	"muscular": "ᕙ(⇀‸↼‶)ᕗ",
	"music": "ヾ(⌐■_■)ノ♪",
	"relieved": "( ͡ᵔ ͜ʖ ͡ᵔ )",
	"orly": "﴾͡๏̯͡๏﴿ O'RLY?",
	"fightme": "(ง'̀-'́)ง",
	"kiss": "(づ￣ ³￣)づ",
	"hug": "(づ｡◕‿‿◕｡)づ",
	"squad": "( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)",
	"judging": "ಠ_ಠ",
	"crying": "(ಥ﹏ಥ)"
}
